// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Metric struct {
	ID    string
	Type  string
	Value sql.NullFloat64
	Delta sql.NullInt64
}
