GET http://localhost:8080/



POST http://localhost:8080/update/
Content-Type: application/json
{"id":"PollCount14", "type": "counter", "delta": 10}

POST http://localhost:8080/update/
Content-Type: application/json
{"id":"PollCount12", "type": "gauge", "value": 10}

POST http://localhost:8080/value/
Content-Type: application/json
HashSHA256: 0b81effaaf74a83a34b2c0e31ee8f7612002ab9f2579530a04ea7318cbaf1109

{"id":"PollCount12"}

GET http://localhost:8080/ping

POST http://localhost:8080/update/counter/TestCounter/10



POST http://localhost:8080/updates/
Content-Type: application/json

[{
    "id": "PollCount19",
    "type": "counter",
    "delta": 10
  },
  {
    "id": "PollCount12",
    "type": "gauge",
    "value": 15
  },
{
    "id": "PollCount19",
    "type": "counter",
    "delta": 10
  }
]