GET http://localhost:8080/


POST http://localhost:8080/update/counter/

POST http://localhost:8080/update/counter/TestCounter/100

POST http://localhost:8080/update/unknown/testCounter/100

GET http://localhost:8080/value/gauge/testUnknown